# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efa35f60acde0cdcf506cf89dc1ae0dacb9d84a7056601e926cf28ff6a5d1f58aaf357ab8bec737fe30a730d046237d3dd6648739d2771b777162f0019eb826b

test:
  secret_key_base: 2483045d84376068341fb6f9d7a760160f3992b45835c24cc6ca90f1c8df2eab38b2e1c57c89c562f14f8fa535cc213c46c772ade19a6fd9db20b2ad4c6d405b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
